### ISSUE TITLE
Pad images to make them the same size

### ISSUE THREAD

**Issue by chr0nikler** [abcde13/devianttagger#4]
Most CNN make sure the images are square before working with them, because convolutions and max pooling steps are easier with square images.

Pad images to make them square after downloading them.

**Comment by cbailey20043** [comment]
Done. Images are 512 x 512. We can change the size easily if thats too large. I think it will be important to get tensorflow running on the GPU to train with these images. It took an hour to train a CNN example I found that used 64 x 64 images (was using CPU though).
